num1=int(input("Enetr a number:"))
if (num1<=100):
    if (num1>=90):
        print("YOU GOT :A")
    elif (num1>=80):
        print("YOU GOT :B")
    elif (num1>=70):
        print("YOU GOT :C")
    elif (num1>=60):
        print("YOU GOT :D")
    elif (num1>=50):
        print("YOU GOT :E")
    elif (num1<=49):
        print("YOU NARE FAIL")
else:
    print ("number should be under 100")